name: flutter_caesium_ffi_example
description: Demonstrates the flutter_caesium_ffi plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_caesium_ffi:
    path: ../

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
