name: flutter_caesium_ffi
description: Fast, high-quality image compression, resize, conversion, and target-size optimization for Flutter mobile, desktop, and web, powered by libcaesium.
version: 2.0.1
homepage: https://github.com/zzzlazy/flutter_caesium_ffi
repository: https://github.com/zzzlazy/flutter_caesium_ffi
issue_tracker: https://github.com/zzzlazy/flutter_caesium_ffi/issues
topics:
  - image
  - image-processing
  - compression
  - ffi
  - wasm

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.10'

dependencies:
  code_assets: ^1.2.1
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  hooks: ^2.0.0

dev_dependencies:
  ffigen: ^20.1.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterCaesiumFfiWeb
        fileName: src/flutter_caesium_ffi_web.dart
  assets:
    - web/libcaesium_wasm/index.js
    - web/libcaesium_wasm/libcaesium_wasm.wasm
