// Generated file. Do not edit.
// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: public_member_api_docs

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Private bindings for the stable flutter_caesium_ffi C ABI.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class FlutterCaesiumFfiBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FlutterCaesiumFfiBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FlutterCaesiumFfiBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int fc_abi_version() {
    return _fc_abi_version();
  }

  late final _fc_abi_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function()>>('fc_abi_version');
  late final _fc_abi_version = _fc_abi_versionPtr.asFunction<int Function()>();

  ffi.Pointer<ffi.Char> fc_native_version() {
    return _fc_native_version();
  }

  late final _fc_native_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'fc_native_version');
  late final _fc_native_version =
      _fc_native_versionPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  int fc_compress_memory(
    ffi.Pointer<ffi.Uint8> input_data,
    int input_length,
    ffi.Pointer<FcOptions> options,
    ffi.Pointer<FcBuffer> output,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_message,
  ) {
    return _fc_compress_memory(
      input_data,
      input_length,
      options,
      output,
      error_message,
    );
  }

  late final _fc_compress_memoryPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(
              ffi.Pointer<ffi.Uint8>,
              ffi.Uint64,
              ffi.Pointer<FcOptions>,
              ffi.Pointer<FcBuffer>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('fc_compress_memory');
  late final _fc_compress_memory = _fc_compress_memoryPtr.asFunction<
      int Function(ffi.Pointer<ffi.Uint8>, int, ffi.Pointer<FcOptions>,
          ffi.Pointer<FcBuffer>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int fc_compress_to_size_memory(
    ffi.Pointer<ffi.Uint8> input_data,
    int input_length,
    int max_output_size,
    int return_smallest,
    ffi.Pointer<FcOptions> options,
    ffi.Pointer<FcBuffer> output,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_message,
  ) {
    return _fc_compress_to_size_memory(
      input_data,
      input_length,
      max_output_size,
      return_smallest,
      options,
      output,
      error_message,
    );
  }

  late final _fc_compress_to_size_memoryPtr = _lookup<
          ffi.NativeFunction<
              ffi.Uint32 Function(
                  ffi.Pointer<ffi.Uint8>,
                  ffi.Uint64,
                  ffi.Uint64,
                  ffi.Uint8,
                  ffi.Pointer<FcOptions>,
                  ffi.Pointer<FcBuffer>,
                  ffi.Pointer<ffi.Pointer<ffi.Char>>)>>(
      'fc_compress_to_size_memory');
  late final _fc_compress_to_size_memory =
      _fc_compress_to_size_memoryPtr.asFunction<
          int Function(
              ffi.Pointer<ffi.Uint8>,
              int,
              int,
              int,
              ffi.Pointer<FcOptions>,
              ffi.Pointer<FcBuffer>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int fc_convert_memory(
    ffi.Pointer<ffi.Uint8> input_data,
    int input_length,
    int output_format,
    ffi.Pointer<FcOptions> options,
    ffi.Pointer<FcBuffer> output,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_message,
  ) {
    return _fc_convert_memory(
      input_data,
      input_length,
      output_format,
      options,
      output,
      error_message,
    );
  }

  late final _fc_convert_memoryPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(
              ffi.Pointer<ffi.Uint8>,
              ffi.Uint64,
              ffi.Uint32,
              ffi.Pointer<FcOptions>,
              ffi.Pointer<FcBuffer>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('fc_convert_memory');
  late final _fc_convert_memory = _fc_convert_memoryPtr.asFunction<
      int Function(ffi.Pointer<ffi.Uint8>, int, int, ffi.Pointer<FcOptions>,
          ffi.Pointer<FcBuffer>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int fc_compress_file(
    ffi.Pointer<ffi.Char> input_path,
    ffi.Pointer<ffi.Char> output_path,
    ffi.Pointer<FcOptions> options,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_message,
  ) {
    return _fc_compress_file(
      input_path,
      output_path,
      options,
      error_message,
    );
  }

  late final _fc_compress_filePtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<FcOptions>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('fc_compress_file');
  late final _fc_compress_file = _fc_compress_filePtr.asFunction<
      int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<FcOptions>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int fc_compress_to_size_file(
    ffi.Pointer<ffi.Char> input_path,
    ffi.Pointer<ffi.Char> output_path,
    int max_output_size,
    int return_smallest,
    ffi.Pointer<FcOptions> options,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_message,
  ) {
    return _fc_compress_to_size_file(
      input_path,
      output_path,
      max_output_size,
      return_smallest,
      options,
      error_message,
    );
  }

  late final _fc_compress_to_size_filePtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Uint64,
              ffi.Uint8,
              ffi.Pointer<FcOptions>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('fc_compress_to_size_file');
  late final _fc_compress_to_size_file =
      _fc_compress_to_size_filePtr.asFunction<
          int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int, int,
              ffi.Pointer<FcOptions>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  int fc_convert_file(
    ffi.Pointer<ffi.Char> input_path,
    ffi.Pointer<ffi.Char> output_path,
    int output_format,
    ffi.Pointer<FcOptions> options,
    ffi.Pointer<ffi.Pointer<ffi.Char>> error_message,
  ) {
    return _fc_convert_file(
      input_path,
      output_path,
      output_format,
      options,
      error_message,
    );
  }

  late final _fc_convert_filePtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Uint32,
              ffi.Pointer<FcOptions>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('fc_convert_file');
  late final _fc_convert_file = _fc_convert_filePtr.asFunction<
      int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int,
          ffi.Pointer<FcOptions>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  void fc_buffer_free(
    ffi.Pointer<FcBuffer> buffer,
  ) {
    return _fc_buffer_free(
      buffer,
    );
  }

  late final _fc_buffer_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FcBuffer>)>>(
          'fc_buffer_free');
  late final _fc_buffer_free =
      _fc_buffer_freePtr.asFunction<void Function(ffi.Pointer<FcBuffer>)>();

  void fc_string_free(
    ffi.Pointer<ffi.Char> string,
  ) {
    return _fc_string_free(
      string,
    );
  }

  late final _fc_string_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'fc_string_free');
  late final _fc_string_free =
      _fc_string_freePtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();
}

/// Image formats accepted by conversion functions.
abstract class FcImageFormat {
  static const int FC_FORMAT_JPEG = 0;
  static const int FC_FORMAT_PNG = 1;
  static const int FC_FORMAT_GIF = 2;
  static const int FC_FORMAT_WEBP = 3;
  static const int FC_FORMAT_TIFF = 4;
}

/// Fixed-width configuration shared by every operation.
final class FcOptions extends ffi.Struct {
  @ffi.Uint8()
  external int keep_metadata;

  @ffi.Uint32()
  external int jpeg_quality;

  @ffi.Uint32()
  external int jpeg_chroma_subsampling;

  @ffi.Uint8()
  external int jpeg_progressive;

  @ffi.Uint8()
  external int jpeg_optimize;

  @ffi.Uint8()
  external int jpeg_preserve_icc;

  @ffi.Uint32()
  external int png_quality;

  @ffi.Uint32()
  external int png_optimization_level;

  @ffi.Uint8()
  external int png_force_zopfli;

  @ffi.Uint8()
  external int png_optimize;

  @ffi.Uint32()
  external int gif_quality;

  @ffi.Uint32()
  external int webp_quality;

  @ffi.Uint8()
  external int webp_lossless;

  @ffi.Uint32()
  external int tiff_compression;

  @ffi.Uint32()
  external int tiff_deflate_level;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;
}

/// Rust-owned output buffer. Release it with fc_buffer_free.
final class FcBuffer extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Uint64()
  external int length;

  @ffi.Uint64()
  external int capacity;
}

const int FC_ABI_VERSION = 1;

const int FC_OK = 0;

const int FC_ERROR_INVALID_ARGUMENT = 20001;

const int FC_ERROR_INVALID_UTF8 = 20002;

const int FC_ERROR_OUTPUT_EXISTS = 20003;

const int FC_ERROR_SAME_PATH = 20004;

const int FC_ERROR_PANIC = 20999;
